-- ===========================================================================
-- Monello Chat (Text-to-SQL) — schema
--
-- Author : Arslonbek Kulmatov
-- Purpose: Xodim tabiiy tilda savol beradi → Claude SQL yozadi → read-only
--          user orqali bajariladi → javob tabiiy tilda qaytadi.
--
-- Xavfsizlik: Claude FAQAT PI_S_CHAT_VIEWS dagi view'larni ko'radi va
-- SQL ham shu ro'yxat bo'yicha tekshiriladi. Bajarilish alohida read-only
-- Oracle user (MONELLO_CHAT_RO) orqali — unda DML/DDL grant umuman yo'q.
-- ===========================================================================


-- ----- 1) Ruxsat berilgan view'lar ro'yxati -------------------------------
Create Table Pi_S_Chat_Views (
  view_name   Varchar2(128) Not Null,
  title_uz    Varchar2(256) Not Null,
  title_ru    Varchar2(256),
  -- Claude'ga beriladigan izoh: ustun konvensiyalari, birliklar, sana formati.
  -- Bu matn to'g'ridan-to'g'ri system prompt'ga tushadi.
  hint        Varchar2(2000),
  is_active   Char(1) Default 'Y',
  order_by    Number(3),
  Constraint Pk_Pi_S_Chat_Views Primary Key (view_name)
);

Insert Into Pi_S_Chat_Views (view_name, title_uz, title_ru, hint, is_active, order_by)
Values ('PI_REGRESS_V', 'Regress ishlari', 'Регрессные дела',
  'Har qator = bitta regress ishi (cover_id unikal). '
  || 'SANA USTUNLARI VARCHAR2, format dd.mm.yyyy: sum_pay_date, contract_date, sent_court_date. '
  || 'Ular bilan solishtirish uchun TO_DATE(ustun, ''dd.mm.yyyy'') ishlating. '
  || 'Summalar so''mda (allaqachon 100 ga bo''lingan): insurance_sum, sum_pay, regres_sum, paid_sum, remaining_debt. '
  || 'debtor_name = qarzdor F.I.O. applicant = ariza beruvchi bank/tashkilot. '
  || 'is_sent_court = ''Да''/''Нет'' (matn), is_sent_court_code = 1/2.',
  'Y', 1);

Insert Into Pi_S_Chat_Views (view_name, title_uz, title_ru, hint, is_active, order_by)
Values ('PI_REGRESS_PAID_AMOUNTS_V', 'Regress to''lovlari', 'Платежи по регрессу',
  'Har qator = bitta to''lov. cover_id orqali PI_REGRESS_V ga bog''lanadi. '
  || 'DIQQAT: paid_date VARCHAR2 (dd.mm.yyyy), pay_date esa haqiqiy DATE. '
  || 'Sana oralig''i bo''yicha filtrlashda pay_date ni ishlating — u tezroq va to''g''ri. '
  || 'paid_amount so''mda. pay_type = to''lov turi nomi (Bank, Incard-uzcard, Pochta xarajatlari, Offline ...).',
  'Y', 2);

Insert Into Pi_S_Chat_Views (view_name, title_uz, title_ru, hint, is_active, order_by)
Values ('PI_DEBTORS_PAID_V', 'To''lagan qarzdorlar (buxgalteriya)', 'Оплатившие должники',
  'Buxgalteriya hisoboti uchun asosiy view. Har qator = qarzini yopgan yoki yarmidan ko''pini to''lagan qarzdor. '
  || 'max_paid_date — haqiqiy DATE (oxirgi to''lov sanasi), sana oralig''i shu ustun bo''yicha olinadi. '
  || 'archive_date VARCHAR2 (dd.mm.yyyy). '
  || 'regres_sum = umumiy qarz, total_paid_amounts = to''langan, remaining_debt = qoldiq (so''mda).',
  'Y', 3);
Commit;

Create Or Replace View Pi_S_Chat_Views_V As
Select view_name, title_uz, title_ru, hint, is_active, order_by
  From Pi_S_Chat_Views
 Where is_active = 'Y'
 Order By order_by;


-- ----- 2) Audit log -------------------------------------------------------
Create Table Pi_Chat_Logs (
  id             Number Generated By Default On Null As Identity,
  user_id        Number(10),
  session_uuid   Varchar2(64),      -- bitta chat suhbatini guruhlash uchun
  question       Varchar2(4000),
  generated_sql  Clob,              -- Claude yozgan SQL (validatsiyadan keyin)
  row_count      Number(10),
  answer         Clob,
  error_msg      Varchar2(4000),
  duration_ms    Number(10),
  input_tokens   Number(10),
  output_tokens  Number(10),
  cr_on          Date Default Sysdate,
  Constraint Pk_Pi_Chat_Logs Primary Key (id)
);

Create Index Ix_Pi_Chat_Logs_User On Pi_Chat_Logs (user_id, cr_on);
Create Index Ix_Pi_Chat_Logs_Session On Pi_Chat_Logs (session_uuid);


-- ===========================================================================
-- 3) READ-ONLY USER — eng muhim himoya qatlami
--
-- Bu user'da INSERT/UPDATE/DELETE/DDL grant UMUMAN yo'q. Claude yozgan SQL
-- qanday bo'lishidan qat'i nazar, ma'lumot o'zgartira olmaydi.
--
-- DBA sifatida bajaring:
-- ===========================================================================

/*
Create User MONELLO_CHAT_RO Identified By "<KUCHLI_PAROL>"
  Default Tablespace USERS
  Temporary Tablespace TEMP
  Quota 0 On USERS;          -- hech narsa yoza olmasin

Grant Create Session To MONELLO_CHAT_RO;

-- Faqat whitelist view'lar uchun SELECT
Grant Select On PSBINSURANCE.PI_REGRESS_V              To MONELLO_CHAT_RO;
Grant Select On PSBINSURANCE.PI_REGRESS_PAID_AMOUNTS_V To MONELLO_CHAT_RO;
Grant Select On PSBINSURANCE.PI_DEBTORS_PAID_V         To MONELLO_CHAT_RO;

-- Schema prompt'ni qurish uchun metadata o'qish (ALL_TAB_COLUMNS o'z-o'zidan
-- faqat grant berilgan obyektlarni ko'rsatadi — qo'shimcha grant shart emas)

-- Core_Session ni o'rnatish uchun (satr darajasidagi filtr ishlashi uchun)
Grant Execute On PSBINSURANCE.CORE_SESSION To MONELLO_CHAT_RO;

-- Synonym'lar (SQL'da schema prefiksi yozilmasin)
Create Or Replace Synonym MONELLO_CHAT_RO.PI_REGRESS_V              For PSBINSURANCE.PI_REGRESS_V;
Create Or Replace Synonym MONELLO_CHAT_RO.PI_REGRESS_PAID_AMOUNTS_V For PSBINSURANCE.PI_REGRESS_PAID_AMOUNTS_V;
Create Or Replace Synonym MONELLO_CHAT_RO.PI_DEBTORS_PAID_V         For PSBINSURANCE.PI_DEBTORS_PAID_V;

-- Resurs cheklovi: bitta so'rov uzoq ketmasin
Create Profile CHAT_RO_PROFILE Limit
  CPU_PER_CALL 3000            -- 30 soniya CPU
  LOGICAL_READS_PER_CALL 5000000
  IDLE_TIME 5
  CONNECT_TIME 60;
Alter User MONELLO_CHAT_RO Profile CHAT_RO_PROFILE;
-- Eslatma: resource_limit=TRUE bo'lishi kerak:
--   Alter System Set resource_limit = TRUE Scope = Both;
*/


-- ----- 4) Yangi view qo'shish tartibi -------------------------------------
-- Chat'ga yangi view ochish uchun IKKALASI ham kerak:
--   1) Insert Into Pi_S_Chat_Views (...) Values ('PI_XXX_V', ...);
--   2) Grant Select On PSBINSURANCE.PI_XXX_V To MONELLO_CHAT_RO;
--      + Create Or Replace Synonym MONELLO_CHAT_RO.PI_XXX_V For PSBINSURANCE.PI_XXX_V;
-- Faqat bittasini qilish yetarli emas — Java tarafi ikkalasini ham tekshiradi.
