-- ===========================================================================
-- FIX: ovoz berish varaqasi majlis kunidagi holatni ko'rsatsin
--
-- MUAMMO
--   23.09.2026 da a'zo "Таътилда" (23.09 — 23.09) edi va o'sha kuni ovoz
--   varaqasida "Таътилда" chiqdi. 24.09 da esa xuddi shu varaqa "Кутилмоқда"
--   ko'rsatyapti.
--
--   Sabab: get_votes va Get_Cover_Info_V2 sababni BUGUNGI kun bilan
--   solishtirardi:
--       When m.reason_to Is Not Null And m.reason_to < Trunc(Sysdate) ...
--   23.09 da  23.09 < 23.09 = false  -> Таътилда
--   24.09 da  23.09 < 24.09 = true   -> PARTICIPATES -> Кутилмоқда
--
--   Ovoz varaqasi — tarixiy hujjat. U majlis kunidagi holatni ko'rsatishi
--   kerak, bugungi holatni emas.
--
-- YECHIM (ikki qism)
--   1) Sabab endi majlis sanasi (pi_committees_v.application_date) bilan
--      solishtiriladi.
--   2) Sabablar tarixi alohida jadvalga yoziladi. Faqat 1-qism yetarli emas:
--      pi_s_committee_members da bitta "hozirgi" sabab saqlanadi, a'zoga
--      keyingi safar boshqa sabab qo'yilishi bilan eski varaqa yana buziladi.
--      Tarix jadvali bo'lsa, istalgan o'tgan sana uchun to'g'ri javob chiqadi.
--
-- QO'LLASH TARTIBI
--   1) Shu fayldagi 1- va 2-bo'limni bajaring (jadval + backfill).
--   2) pi_committee_body.sql ni to'liq bajaring (PI_COMMITTEE paketi).
--   3) PI_METHODS body ichida Get_Cover_Info_V2 ning votes loop'ini
--      shu fayldagi 3-bo'lim bilan almashtiring va paketni kompilyatsiya qiling.
--   4) 4-bo'limdagi tekshiruvlarni bajaring.
--
-- Talab: committee_member_absence.sql allaqachon qo'llangan bo'lishi kerak.
-- ===========================================================================


-- ----- 1) Sabablar tarixi jadvali ----------------------------------------
Create Table Pi_S_Committee_Member_Absences (
  id        Number(20) Generated By Default On Null As Identity,
  user_id   Number(10)   Not Null,
  reason    Varchar2(32) Not Null,
  date_from Date         Not Null,
  date_to   Date,                      -- Null = muddatsiz (hali tugamagan)
  note      Varchar2(512),
  cr_by     Number(10),
  cr_on     Date Default Sysdate,
  Constraint Pk_Pi_S_Com_Mem_Absences Primary Key (id),
  Constraint Fk_Pi_S_Com_Mem_Abs_Reason
    Foreign Key (reason) References Pi_S_Committee_Absence_Reasons (code),
  Constraint Ck_Pi_S_Com_Mem_Abs_Dates
    Check (date_to Is Null Or date_to >= date_from)
);

Create Index Ix_Pi_S_Com_Mem_Abs_User
  On Pi_S_Committee_Member_Absences (user_id, date_from, date_to);


-- ----- 2) Backfill: hozirgi sabablarni tarixga ko'chirish -----------------
--
-- ESKI MA'LUMOT HAQIDA OCHIQ GAP:
--   Pi_S_Committee_Members_his da reason ustunlari YO'Q (faqat position,
--   name, order_by, added_on, expired_on saqlanadi). Demak ilgarigi
--   sabablarni hech qayerdan tiklab bo'lmaydi — ular hech qachon
--   yozilmagan.
--
--   Tiklash mumkin bo'lgan yagona narsa — Pi_S_Committee_Members dagi
--   HOZIRGI qiymatlar. Ular quyidagi backfill bilan ko'chiriladi va shu
--   hozircha yetarli, chunki 23.09 dagi taътil aynan shu yerda turibdi:
--
--     user_id 240  С.К.Бегматов    BUSINESS_TRIP  12.09.2026 - 17.09.2026
--     user_id 198  А.А.Халилов     BUSINESS_TRIP  12.09.2026 - 17.09.2026
--     user_id 242  Х.Ж.Холбутаев   VACATION       23.09.2026 - 23.09.2026
--
--   Bundan keyin har bir o'zgarish Pi_S_Committee_Member_Absences ga
--   yoziladi va boshqa yo'qolmaydi.
--
--   Undan ham eski davrlarni bilsangiz, 2a-bo'limdagi shablon bilan
--   qo'lda kiritishingiz mumkin.
Insert Into Pi_S_Committee_Member_Absences
  (user_id, reason, date_from, date_to, note, cr_by, cr_on)
Select m.user_id,
       m.current_reason,
       Nvl(m.reason_from, Trunc(Nvl(m.reason_set_on, m.added_on))),
       m.reason_to,
       m.reason_note,
       m.reason_set_by,
       Nvl(m.reason_set_on, Sysdate)
  From Pi_S_Committee_Members m
 Where m.current_reason Is Not Null
   And m.current_reason <> 'PARTICIPATES'
   And Nvl(m.reason_from, Trunc(Nvl(m.reason_set_on, m.added_on))) Is Not Null;
Commit;

-- Backfill natijasini ko'rish (3 ta qator kutiladi):
--   Select a.user_id, m.name, a.reason, a.date_from, a.date_to, a.note
--     From Pi_S_Committee_Member_Absences a
--     Join Pi_S_Committee_Members m On m.user_id = a.user_id
--    Order By a.date_from;


-- ----- 2a) Eski davrni qo'lda kiritish shabloni ---------------------------
-- Faqat kerak bo'lsa. Bir a'zo bir vaqtning o'zida bir davrda bo'lishi
-- kerak — davrlar ustma-ust tushmasin.
--
--   Insert Into Pi_S_Committee_Member_Absences
--     (user_id, reason, date_from, date_to, note, cr_by, cr_on)
--   Values
--     (242,                                   -- kim
--      'VACATION',                            -- PARTICIPATES/BUSINESS_TRIP/
--                                             -- VACATION/SICK_LEAVE/OTHER
--      To_Date('15.08.2026', 'dd.mm.yyyy'),   -- boshlanishi
--      To_Date('20.08.2026', 'dd.mm.yyyy'),   -- tugashi (Null = muddatsiz)
--      'qo''lda kiritildi',                   -- izoh
--      Core_Session.Get_User_Id, Sysdate);
--   Commit;
--
-- Ustma-ust tushgan davrlarni tekshirish:
--   Select a1.user_id, a1.id, a1.date_from, a1.date_to,
--          a2.id, a2.date_from, a2.date_to
--     From Pi_S_Committee_Member_Absences a1
--     Join Pi_S_Committee_Member_Absences a2
--       On a2.user_id = a1.user_id
--      And a2.id > a1.id
--      And a1.date_from <= Nvl(a2.date_to, To_Date('31.12.9999','dd.mm.yyyy'))
--      And a2.date_from <= Nvl(a1.date_to, To_Date('31.12.9999','dd.mm.yyyy'));


-- ===========================================================================
-- 3) Pi_Methods.Get_Cover_Info_V2 — PDF/bosma varaqa ham aynan shu xatoga
--    uchragan (3-skrinshot).
--
-- QADAM 1. Protsedura e'lon (Is) qismiga BITTA o'zgaruvchi qo'shing.
--          Mavjud qatorlar orasiga, masalan v_Row dan keyin:
--
--              v_Row            pi_committees_v%rowtype;
--              vApp_Date        Date;                      -- <<< QO'SHILADI
--
-- QADAM 2. "If vCommittee_Id Is Not Null Then" dan boshlab, unga mos
--          "End If;" gacha bo'lgan butun blokni quyidagi bilan almashtiring
--          (qrcode/payout qismlari o'zgarishsiz, nusxalash qulay bo'lsin
--          uchun kiritilgan).
-- ===========================================================================

/*
		If vCommittee_Id Is Not Null Then

		  -- Majlis sanasi — barcha a'zolar uchun bitta.
		  -- Ilgari bu Select har bir a'zo uchun loop ichida qayta bajarilardi.
		  Begin
		    Select k.* Into v_Row
		      From pi_committees_v k
		     Where k.id = vCommittee_Id;
		    vApp_Date := To_Date(v_Row.APPLICATION_DATE, 'dd.mm.yyyy');
		  Exception When Others Then
		    vApp_Date := Trunc(Sysdate);
		  End;
		  If vApp_Date Is Null Then
		    vApp_Date := Trunc(Sysdate);
		  End If;

		  For i In (Select
		              m.user_id,
		              m.name,
		              m.position,
		              Nvl(m.added_on, To_Date('01.11.2025', 'dd.mm.yyyy')) added_on,
		              m.expired_on,
		              Nvl(ab.reason, 'PARTICIPATES') effective_reason,
		              ab.note                        effective_note
		            From pi_s_committee_members m
		            Outer Apply (Select a.reason, a.note
		                           From Pi_S_Committee_Member_Absences a
		                          Where a.user_id = m.user_id
		                            And a.date_from <= vApp_Date
		                            And (a.date_to Is Null Or a.date_to >= vApp_Date)
		                          Order By a.date_from Desc, a.id Desc
		                          Fetch First 1 Row Only) ab
		            Order By m.order_by) Loop

		    -- A'zolik muddati majlis sanasini qamrab olmasa — ro'yxatga tushmaydi
		    If i.added_on   Is Not Null And vApp_Date < i.added_on   Then Continue; End If;
		    If i.expired_on Is Not Null And vApp_Date > i.expired_on Then Continue; End If;

		    Declare
		      v_ReasonName Varchar2(128);
		      v_Color      Varchar2(16);
		    Begin
		      Begin
		        Select name_uz, color
		          Into v_ReasonName, v_Color
		          From Pi_S_Committee_Absence_Reasons
		         Where code = i.effective_reason;
		      Exception When No_Data_Found Then
		        v_ReasonName := 'Иштирок этади';
		        v_Color      := 'success';
		      End;

		      If i.effective_reason = 'PARTICIPATES' Then
		        Begin
		          Select v.vote, v.comments, To_Char(v.vote_on, 'dd.mm.yyyy hh24:mi:ss')
		            Into vVote, vComments, vVote_On
		            From pi_committee_member_votes v
		           Where v.user_id = i.user_id
		             And v.committee_id = vCommittee_Id;
		        Exception When No_Data_Found Then
		          vVote     := 'Кутилмоқда';
		          vVote_On  := Null;
		          vComments := Null;
		        End;
		      Else
		        -- Ovoz kutilmaydi — sabab ko'rsatiladi
		        vVote     := v_ReasonName;
		        vVote_On  := Null;
		        vComments := i.effective_note;
		      End If;

		      vVote_Obj := Json_Object_t();
		      vVote_Obj.Put('committee_id',  vCommittee_Id);
		      vVote_Obj.Put('user_id',       i.user_id);
		      vVote_Obj.Put('user_name',     i.name);
		      vVote_Obj.Put('role',          i.position);
		      vVote_Obj.Put('vote',          vVote);
		      vVote_Obj.Put('vote_on',       vVote_On);
		      vVote_Obj.Put('comments',      vComments);
		      vVote_Obj.Put('reason',        i.effective_reason);
		      vVote_Obj.Put('reason_name',   v_ReasonName);
		      vVote_Obj.Put('reason_color',  v_Color);
		      vVote_Obj.Put('is_voter',      Case When i.effective_reason = 'PARTICIPATES'
		                                          Then 'Y' Else 'N' End);

		      vVotes_Arr.Append(vVote_Obj);
		    End;
		  End Loop;

		  Begin
		    Select t.url
		      Into vQr_Code_Url
		      From pi_committee_files t
		     Where t.committee_id = vCommittee_Id
		       And t.type = 'DECISION'
		       And t.state = 'A';
		  Exception
		    When no_data_found Then
		      vQr_Code_Url := Null;
		  End;

		  Begin
		    Select t.url
		      Into vPayout_Url
		      From pi_committee_files t
		     Where t.committee_id = vCommittee_Id
		       And t.type = 'PAYOUT'
		       And t.state = 'A';
		  Exception
		    When no_data_found Then
		      vPayout_Url := Null;
		  End;

		  vObj.put('payout_url', vPayout_Url);
		  vObj.put('qrcode_url', vQr_Code_Url);
		End If;
*/

-- ESKI kodda nima noto'g'ri edi (solishtirish uchun):
--
--   Case
--     When m.reason_to Is Not Null And m.reason_to < Trunc(Sysdate) Then 'PARTICIPATES'
--     Else Nvl(m.current_reason, 'PARTICIPATES')
--   End effective_reason
--
-- Bu yerda Sysdate — hisobot ochilgan kun. Majlis kuni bilan aloqasi yo'q.
-- Yana bir kamchilik: "Select k.* Into v_Row From pi_committees_v" loop
-- ICHIDA edi, ya'ni har bir a'zo uchun qayta bajarilardi.


-- ===========================================================================
-- 4) Tekshirish
-- ===========================================================================

-- 4a. Backfill tushganini ko'rish (23.09 dagi taътil shu yerda bo'lishi kerak):
--   Select a.user_id, m.name, a.reason, a.date_from, a.date_to, a.note
--     From Pi_S_Committee_Member_Absences a
--     Join Pi_S_Committee_Members m On m.user_id = a.user_id
--    Order By a.date_from Desc;

-- 4b. Muayyan sana uchun kim qaysi holatda bo'lganini ko'rish:
--   Select m.name,
--          Nvl(ab.reason, 'PARTICIPATES') reason,
--          ab.note
--     From Pi_S_Committee_Members m
--     Outer Apply (Select a.reason, a.note
--                    From Pi_S_Committee_Member_Absences a
--                   Where a.user_id = m.user_id
--                     And a.date_from <= To_Date('23.09.2026', 'dd.mm.yyyy')
--                     And (a.date_to Is Null
--                          Or a.date_to >= To_Date('23.09.2026', 'dd.mm.yyyy'))
--                   Order By a.date_from Desc, a.id Desc
--                   Fetch First 1 Row Only) ab
--    Order By m.order_by;

-- 4c. Paketlarni kompilyatsiya qilgach:
--     - 23.09 dagi majlisni oching: Х.Ж.Холбутаев qatorida "Таътилда"
--       chiqishi kerak, "Кутилмоқда" emas. PDF'da ham shunday.
--     - Bugungi majlisda esa u yana "Кутилмоқда" (ovoz kutilmoqda) bo'ladi,
--       chunki taътil kecha tugagan — bu to'g'ri xatti-harakat.
